package Vistas;

import javax.swing.JPanel;

public class FichaClinica extends javax.swing.JFrame {

    /**
     * Creates new form Preempleo
     */
    public String nombreContenido = "Ficha Clínica";
    public FichaClinica() {
        initComponents();
    }
    
    public JPanel getContenido(){
        return cont_FichaClinica;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cont_FichaClinica = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cont_FichaClinica.setBackground(new java.awt.Color(255, 255, 255));
        cont_FichaClinica.setPreferredSize(new java.awt.Dimension(1080, 600));
        cont_FichaClinica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ficha Clínica");
        cont_FichaClinica.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 50, 1080, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cont_FichaClinica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cont_FichaClinica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cont_FichaClinica;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
