package Vistas;

import javax.swing.JPanel;

public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Preempleo
     */
    public String nombreContenido = "Dashboard";
    public Inicio() {
        initComponents();
    }
    
    public JPanel getContenido(){
        return cont_Dashboard;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cont_Dashboard = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cont_Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        cont_Dashboard.setPreferredSize(new java.awt.Dimension(1080, 600));
        cont_Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDashboard.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDashboard.setText("Bienvenido");
        cont_Dashboard.add(lblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 50, 1080, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setText("Ingrese a una Ficha Médica en el panel izquierdo");
        cont_Dashboard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 520, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cont_Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cont_Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cont_Dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDashboard;
    // End of variables declaration//GEN-END:variables
}
