package Vistas;

import java.awt.Color;
import Utilitarios.Utilitarios;
import java.awt.BorderLayout;
import java.awt.event.MouseEvent;
import java.net.ConnectException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

public class MenuPrincipal extends javax.swing.JFrame {

    Utilitarios util = new Utilitarios();
    JPanel nuevoContenido = new JPanel();
    int xMouse, yMouse;
    public String usuario_id;
    String contenidoActual = "";
    public MenuPrincipal() {
        initComponents();
        construirEtiquetas();
        txt_Home.setIcon(util.construirImagen("/Imagenes/Home.png", txt_Home.getWidth(), txt_Home.getHeight()));
        Dashboard dashboard = new Dashboard();
        nuevoContenido = dashboard.getContenido();
        cambioContenido(nuevoContenido, dashboard.nombreContenido);
        //contenido.removeAll();
    }
    
    private void construirEtiquetas(){
        txt_FichaAccidente.setText("<html>&emsp;Ficha Accidente</html>");
        txt_EvaluacionPeriodica.setText("<html>&emsp;Ficha Clínica</html>");
        txt_PacienteCronico.setText("<html>&emsp;Seguimiento Pacientes<br>&emsp;Crónicos</html>");
        txt_Preempleo.setText("<html>&emsp;Ficha Preempleo</html>");
        txt_EvaluacionPeriodica.setText("<html>&emsp;Revisión Periódica</html>");
        txt_VidaSaludable.setText("<html>&emsp;Seguimiento Vida<br>&emsp;Saludable</html>");
        txt_HojaReferencia.setText("<html>&emsp;Hoja de Referencia</html>");
        txt_Reportes.setText("<html>&emsp;Hoja de Reportes</html>");
    }
    
    private void cambioContenido(JPanel panel, String nombreContenido){
        contenido.removeAll();
        contenido.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        contenido.revalidate();
        contenido.repaint();
        contenidoActual = nombreContenido;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barra = new javax.swing.JPanel();
        exit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        barraOpciones = new javax.swing.JPanel();
        btn_Home = new javax.swing.JPanel();
        txt_Home = new javax.swing.JLabel();
        btn_Preempleo = new javax.swing.JPanel();
        txt_Preempleo = new javax.swing.JLabel();
        btn_FichaClinica = new javax.swing.JPanel();
        txt_FichaClinica = new javax.swing.JLabel();
        btn_EvaluacionPeriodica = new javax.swing.JPanel();
        txt_EvaluacionPeriodica = new javax.swing.JLabel();
        btn_HojaReferencia = new javax.swing.JPanel();
        txt_HojaReferencia = new javax.swing.JLabel();
        btn_PacienteCronico = new javax.swing.JPanel();
        txt_PacienteCronico = new javax.swing.JLabel();
        btn_SeguimientoVidaSaludable = new javax.swing.JPanel();
        txt_VidaSaludable = new javax.swing.JLabel();
        btn_FichaAccidente = new javax.swing.JPanel();
        txt_FichaAccidente = new javax.swing.JLabel();
        btn_Reevaluacion = new javax.swing.JPanel();
        txt_Reevaluacion = new javax.swing.JLabel();
        btn_Reincorporacion = new javax.swing.JPanel();
        txt_Reincorporacion = new javax.swing.JLabel();
        btn_Reportes = new javax.swing.JPanel();
        txt_Reportes = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMouseDragged(evt);
            }
        });
        barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMousePressed(evt);
            }
        });

        txtExit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("X");
        txtExit.setMaximumSize(new java.awt.Dimension(40, 40));
        txtExit.setPreferredSize(new java.awt.Dimension(40, 40));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitLayout = new javax.swing.GroupLayout(exit);
        exit.setLayout(exitLayout);
        exitLayout.setHorizontalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitLayout.createSequentialGroup()
                .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        exitLayout.setVerticalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitLayout.createSequentialGroup()
                .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout barraLayout = new javax.swing.GroupLayout(barra);
        barra.setLayout(barraLayout);
        barraLayout.setHorizontalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLayout.createSequentialGroup()
                .addGap(0, 1240, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barraLayout.setVerticalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 40));

        barraOpciones.setBackground(new java.awt.Color(172, 211, 227));
        barraOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Home.setBackground(new java.awt.Color(172, 211, 227));
        btn_Home.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HomeMouseExited(evt);
            }
        });
        btn_Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_HomeMouseExited(evt);
            }
        });
        btn_Home.add(txt_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 0, 50, 50));

        barraOpciones.add(btn_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        btn_Preempleo.setBackground(new java.awt.Color(195, 200, 230));
        btn_Preempleo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Preempleo.setPreferredSize(new java.awt.Dimension(200, 40));
        btn_Preempleo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Preempleo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_Preempleo.setText("Preempleo");
        txt_Preempleo.setToolTipText("");
        txt_Preempleo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_Preempleo.setMaximumSize(new java.awt.Dimension(200, 40));
        txt_Preempleo.setMinimumSize(new java.awt.Dimension(200, 40));
        txt_Preempleo.setPreferredSize(new java.awt.Dimension(200, 40));
        txt_Preempleo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_PreempleoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_PreempleoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_PreempleoMouseExited(evt);
            }
        });
        btn_Preempleo.add(txt_Preempleo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        barraOpciones.add(btn_Preempleo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 40));

        btn_FichaClinica.setBackground(new java.awt.Color(172, 180, 227));
        btn_FichaClinica.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_FichaClinica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_FichaClinica.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_FichaClinica.setText("Ficha Clínica");
        txt_FichaClinica.setToolTipText("");
        txt_FichaClinica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_FichaClinica.setMaximumSize(new java.awt.Dimension(200, 40));
        txt_FichaClinica.setMinimumSize(new java.awt.Dimension(200, 40));
        txt_FichaClinica.setPreferredSize(new java.awt.Dimension(200, 40));
        txt_FichaClinica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_FichaClinicaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_FichaClinicaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_FichaClinicaMouseExited(evt);
            }
        });
        btn_FichaClinica.add(txt_FichaClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        barraOpciones.add(btn_FichaClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 200, 40));

        btn_EvaluacionPeriodica.setBackground(new java.awt.Color(195, 200, 230));
        btn_EvaluacionPeriodica.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_EvaluacionPeriodica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_EvaluacionPeriodica.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_EvaluacionPeriodica.setText("Evaluación Periódica");
        txt_EvaluacionPeriodica.setToolTipText("");
        txt_EvaluacionPeriodica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_EvaluacionPeriodica.setMaximumSize(new java.awt.Dimension(200, 40));
        txt_EvaluacionPeriodica.setMinimumSize(new java.awt.Dimension(200, 40));
        txt_EvaluacionPeriodica.setPreferredSize(new java.awt.Dimension(200, 40));
        txt_EvaluacionPeriodica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_EvaluacionPeriodicaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_EvaluacionPeriodicaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_EvaluacionPeriodicaMouseExited(evt);
            }
        });
        btn_EvaluacionPeriodica.add(txt_EvaluacionPeriodica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        barraOpciones.add(btn_EvaluacionPeriodica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 40));

        btn_HojaReferencia.setBackground(new java.awt.Color(172, 180, 227));
        btn_HojaReferencia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_HojaReferencia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_HojaReferencia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_HojaReferencia.setText("Hoja de Referencia");
        txt_HojaReferencia.setToolTipText("");
        txt_HojaReferencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_HojaReferencia.setMaximumSize(new java.awt.Dimension(200, 40));
        txt_HojaReferencia.setMinimumSize(new java.awt.Dimension(200, 40));
        txt_HojaReferencia.setPreferredSize(new java.awt.Dimension(200, 40));
        txt_HojaReferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_HojaReferenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_HojaReferenciaMouseExited(evt);
            }
        });
        btn_HojaReferencia.add(txt_HojaReferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        barraOpciones.add(btn_HojaReferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 200, 40));

        btn_PacienteCronico.setBackground(new java.awt.Color(195, 200, 230));
        btn_PacienteCronico.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_PacienteCronico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_PacienteCronico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_PacienteCronico.setText("Seguimiento Pacientes Crónicos");
        txt_PacienteCronico.setToolTipText("");
        txt_PacienteCronico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_PacienteCronico.setMaximumSize(new java.awt.Dimension(200, 40));
        txt_PacienteCronico.setMinimumSize(new java.awt.Dimension(200, 40));
        txt_PacienteCronico.setPreferredSize(new java.awt.Dimension(200, 40));
        btn_PacienteCronico.add(txt_PacienteCronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        barraOpciones.add(btn_PacienteCronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 40));

        btn_SeguimientoVidaSaludable.setBackground(new java.awt.Color(172, 180, 227));
        btn_SeguimientoVidaSaludable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_SeguimientoVidaSaludable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_VidaSaludable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_VidaSaludable.setText("Vida Saludable");
        txt_VidaSaludable.setToolTipText("");
        txt_VidaSaludable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_VidaSaludable.setMaximumSize(new java.awt.Dimension(200, 40));
        txt_VidaSaludable.setMinimumSize(new java.awt.Dimension(200, 40));
        txt_VidaSaludable.setPreferredSize(new java.awt.Dimension(200, 40));
        txt_VidaSaludable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_VidaSaludableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_VidaSaludableMouseExited(evt);
            }
        });
        btn_SeguimientoVidaSaludable.add(txt_VidaSaludable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        barraOpciones.add(btn_SeguimientoVidaSaludable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 40));

        btn_FichaAccidente.setBackground(new java.awt.Color(195, 200, 230));
        btn_FichaAccidente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_FichaAccidente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_FichaAccidente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_FichaAccidente.setText("Ficha Accidente");
        txt_FichaAccidente.setToolTipText("");
        txt_FichaAccidente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_FichaAccidente.setMaximumSize(new java.awt.Dimension(200, 40));
        txt_FichaAccidente.setMinimumSize(new java.awt.Dimension(200, 40));
        txt_FichaAccidente.setPreferredSize(new java.awt.Dimension(200, 40));
        txt_FichaAccidente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_FichaAccidenteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_FichaAccidenteMouseExited(evt);
            }
        });
        btn_FichaAccidente.add(txt_FichaAccidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        barraOpciones.add(btn_FichaAccidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 200, 40));

        btn_Reevaluacion.setBackground(new java.awt.Color(172, 180, 227));
        btn_Reevaluacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Reevaluacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Reevaluacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_Reevaluacion.setText("Reevaluación Preempleo");
        txt_Reevaluacion.setToolTipText("");
        txt_Reevaluacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_Reevaluacion.setMaximumSize(new java.awt.Dimension(200, 40));
        txt_Reevaluacion.setMinimumSize(new java.awt.Dimension(200, 40));
        txt_Reevaluacion.setPreferredSize(new java.awt.Dimension(200, 40));
        txt_Reevaluacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_ReevaluacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_ReevaluacionMouseExited(evt);
            }
        });
        btn_Reevaluacion.add(txt_Reevaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        barraOpciones.add(btn_Reevaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 200, 40));

        btn_Reincorporacion.setBackground(new java.awt.Color(172, 180, 227));
        btn_Reincorporacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Reincorporacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Reincorporacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_Reincorporacion.setText("Reincorporación Laboral");
        txt_Reincorporacion.setToolTipText("");
        txt_Reincorporacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_Reincorporacion.setMaximumSize(new java.awt.Dimension(200, 40));
        txt_Reincorporacion.setMinimumSize(new java.awt.Dimension(200, 40));
        txt_Reincorporacion.setPreferredSize(new java.awt.Dimension(200, 40));
        txt_Reincorporacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_ReincorporacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_ReincorporacionMouseExited(evt);
            }
        });
        btn_Reincorporacion.add(txt_Reincorporacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        barraOpciones.add(btn_Reincorporacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 200, 40));

        btn_Reportes.setBackground(new java.awt.Color(172, 180, 227));
        btn_Reportes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Reportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Reportes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_Reportes.setText("Reportes");
        txt_Reportes.setToolTipText("");
        txt_Reportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_Reportes.setMaximumSize(new java.awt.Dimension(200, 40));
        txt_Reportes.setMinimumSize(new java.awt.Dimension(200, 40));
        txt_Reportes.setPreferredSize(new java.awt.Dimension(200, 40));
        txt_Reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_ReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_ReportesMouseExited(evt);
            }
        });
        btn_Reportes.add(txt_Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        barraOpciones.add(btn_Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 200, 40));

        jPanel1.add(barraOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 600));

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 1080, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        exit.setBackground(Color.red);
        txtExit.setForeground(Color.white);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        exit.setBackground(barra.getBackground());
        txtExit.setForeground(Color.black);
    }//GEN-LAST:event_txtExitMouseExited

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtExitMouseClicked

    private void barraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraMousePressed

    private void barraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraMouseDragged

    private void txt_PreempleoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_PreempleoMouseEntered
        btn_Preempleo.setBackground(util.colorCursorEntra(btn_Preempleo.getBackground()));
    }//GEN-LAST:event_txt_PreempleoMouseEntered

    private void txt_PreempleoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_PreempleoMouseExited
        btn_Preempleo.setBackground(util.colorCursorSale(btn_Preempleo.getBackground()));
    }//GEN-LAST:event_txt_PreempleoMouseExited

    private void txt_FichaClinicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_FichaClinicaMouseEntered
        btn_FichaClinica.setBackground(util.colorCursorEntra(btn_FichaClinica.getBackground()));
    }//GEN-LAST:event_txt_FichaClinicaMouseEntered

    private void txt_FichaClinicaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_FichaClinicaMouseExited
        btn_FichaClinica.setBackground(util.colorCursorSale(btn_FichaClinica.getBackground()));
    }//GEN-LAST:event_txt_FichaClinicaMouseExited

    private void txt_VidaSaludableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_VidaSaludableMouseEntered
        btn_SeguimientoVidaSaludable.setBackground(util.colorCursorEntra(btn_SeguimientoVidaSaludable.getBackground()));
    }//GEN-LAST:event_txt_VidaSaludableMouseEntered

    private void txt_VidaSaludableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_VidaSaludableMouseExited
        btn_SeguimientoVidaSaludable.setBackground(util.colorCursorSale(btn_SeguimientoVidaSaludable.getBackground()));
    }//GEN-LAST:event_txt_VidaSaludableMouseExited

    private void txt_FichaAccidenteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_FichaAccidenteMouseEntered
        btn_FichaAccidente.setBackground(util.colorCursorEntra(btn_FichaAccidente.getBackground()));
    }//GEN-LAST:event_txt_FichaAccidenteMouseEntered

    private void txt_FichaAccidenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_FichaAccidenteMouseExited
        btn_FichaAccidente.setBackground(util.colorCursorSale(btn_FichaAccidente.getBackground()));
    }//GEN-LAST:event_txt_FichaAccidenteMouseExited

    private void txt_EvaluacionPeriodicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_EvaluacionPeriodicaMouseEntered
        btn_EvaluacionPeriodica.setBackground(util.colorCursorEntra(btn_EvaluacionPeriodica.getBackground()));
    }//GEN-LAST:event_txt_EvaluacionPeriodicaMouseEntered

    private void txt_EvaluacionPeriodicaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_EvaluacionPeriodicaMouseExited
        btn_EvaluacionPeriodica.setBackground(util.colorCursorSale(btn_EvaluacionPeriodica.getBackground()));
    }//GEN-LAST:event_txt_EvaluacionPeriodicaMouseExited

    private void txt_ReevaluacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ReevaluacionMouseEntered
        btn_Reevaluacion.setBackground(util.colorCursorEntra(btn_Reevaluacion.getBackground()));
    }//GEN-LAST:event_txt_ReevaluacionMouseEntered

    private void txt_ReincorporacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ReincorporacionMouseEntered
        btn_Reincorporacion.setBackground(util.colorCursorEntra(btn_Reincorporacion.getBackground()));
    }//GEN-LAST:event_txt_ReincorporacionMouseEntered

    private void txt_ReincorporacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ReincorporacionMouseExited
        btn_Reincorporacion.setBackground(util.colorCursorSale(btn_Reincorporacion.getBackground()));
    }//GEN-LAST:event_txt_ReincorporacionMouseExited

    private void txt_HojaReferenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_HojaReferenciaMouseEntered
        btn_HojaReferencia.setBackground(util.colorCursorEntra(btn_HojaReferencia.getBackground()));
    }//GEN-LAST:event_txt_HojaReferenciaMouseEntered

    private void txt_HojaReferenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_HojaReferenciaMouseExited
        btn_HojaReferencia.setBackground(util.colorCursorSale(btn_HojaReferencia.getBackground()));
    }//GEN-LAST:event_txt_HojaReferenciaMouseExited

    private void txt_ReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ReportesMouseEntered
        btn_Reportes.setBackground(util.colorCursorEntra(btn_Reportes.getBackground()));
    }//GEN-LAST:event_txt_ReportesMouseEntered

    private void txt_ReevaluacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ReevaluacionMouseExited
        btn_Reevaluacion.setBackground(util.colorCursorSale(btn_Reevaluacion.getBackground()));
    }//GEN-LAST:event_txt_ReevaluacionMouseExited

    private void txt_ReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ReportesMouseExited
        btn_Reportes.setBackground(util.colorCursorSale(btn_Reportes.getBackground()));
    }//GEN-LAST:event_txt_ReportesMouseExited

    private void btn_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseEntered
        btn_Home.setBackground(util.colorCursorEntra(btn_Home.getBackground()));
    }//GEN-LAST:event_btn_HomeMouseEntered

    private void txt_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_HomeMouseEntered
        btn_Home.setBackground(util.colorCursorEntra(btn_Home.getBackground()));
    }//GEN-LAST:event_txt_HomeMouseEntered

    private void btn_HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseExited
        btn_Home.setBackground(util.colorCursorSale(btn_Home.getBackground()));
    }//GEN-LAST:event_btn_HomeMouseExited

    private void txt_HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_HomeMouseExited
        btn_Home.setBackground(util.colorCursorSale(btn_Home.getBackground()));
    }//GEN-LAST:event_txt_HomeMouseExited

    private void txt_PreempleoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_PreempleoMouseClicked
        try {
            Preempleo preempleo = new Preempleo();
            if (!preempleo.nombreContenido.equals(contenidoActual)){
                preempleo.responsable = usuario_id;
                nuevoContenido = preempleo.getContenido();
                cambioContenido(nuevoContenido, preempleo.nombreContenido);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ConnectException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }catch (Exception ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_txt_PreempleoMouseClicked

    private void txt_FichaClinicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_FichaClinicaMouseClicked
        try{
            ConsultaGeneral consultaGeneral= new ConsultaGeneral();
            if (!consultaGeneral.nombreContenido.equals(contenidoActual)){
                consultaGeneral.responsable = usuario_id;
                nuevoContenido = consultaGeneral.getContenido();
                cambioContenido(nuevoContenido, consultaGeneral.nombreContenido);
            }
        }catch (Exception ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        } 
    }//GEN-LAST:event_txt_FichaClinicaMouseClicked

    private void btn_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMouseClicked
        Dashboard dashboard = new Dashboard();
        if (!dashboard.nombreContenido.equals(contenidoActual)){
            nuevoContenido = dashboard.getContenido();
            cambioContenido(nuevoContenido, dashboard.nombreContenido);
        }
    }//GEN-LAST:event_btn_HomeMouseClicked

    private void txt_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_HomeMouseClicked
        Dashboard dashboard = new Dashboard();
        if (!dashboard.nombreContenido.equals(contenidoActual)){
            nuevoContenido = dashboard.getContenido();
            cambioContenido(nuevoContenido, dashboard.nombreContenido);
        }
    }//GEN-LAST:event_txt_HomeMouseClicked

    private void txt_EvaluacionPeriodicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_EvaluacionPeriodicaMouseClicked

        try{
            EvaluacionPeriodica evaluacionPeriodica = new EvaluacionPeriodica();
            if (!evaluacionPeriodica.nombreContenido.equals(contenidoActual)){
                evaluacionPeriodica.responsable = usuario_id;
                nuevoContenido = evaluacionPeriodica.getContenido();
                cambioContenido(nuevoContenido, evaluacionPeriodica.nombreContenido);
            }
        }catch (Exception ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        } 
    }//GEN-LAST:event_txt_EvaluacionPeriodicaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra;
    private javax.swing.JPanel barraOpciones;
    private javax.swing.JPanel btn_EvaluacionPeriodica;
    private javax.swing.JPanel btn_FichaAccidente;
    private javax.swing.JPanel btn_FichaClinica;
    private javax.swing.JPanel btn_HojaReferencia;
    private javax.swing.JPanel btn_Home;
    private javax.swing.JPanel btn_PacienteCronico;
    private javax.swing.JPanel btn_Preempleo;
    private javax.swing.JPanel btn_Reevaluacion;
    private javax.swing.JPanel btn_Reincorporacion;
    private javax.swing.JPanel btn_Reportes;
    private javax.swing.JPanel btn_SeguimientoVidaSaludable;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtExit;
    private javax.swing.JLabel txt_EvaluacionPeriodica;
    private javax.swing.JLabel txt_FichaAccidente;
    private javax.swing.JLabel txt_FichaClinica;
    private javax.swing.JLabel txt_HojaReferencia;
    private javax.swing.JLabel txt_Home;
    private javax.swing.JLabel txt_PacienteCronico;
    private javax.swing.JLabel txt_Preempleo;
    private javax.swing.JLabel txt_Reevaluacion;
    private javax.swing.JLabel txt_Reincorporacion;
    private javax.swing.JLabel txt_Reportes;
    private javax.swing.JLabel txt_VidaSaludable;
    // End of variables declaration//GEN-END:variables
}
